### ISSUE TITLE
Doubt 

### ISSUE THREAD

**Issue by pedroalbanese** [howeyc/sc#1]
How to sum fields between two cells, such as @sum(B1:B9) ?

Thanks.

**Comment by howeyc** [comment]
This project is very simplistic. I didn't implement any functions. To do that you would have to set the field to "=B1+B2+B3+B4+B5+B6+B7+B8+B9"

**Comment by pedroalbanese** [comment]
It's very useful and runs on my smarphone. I wondered if it would not be possible to have a command that would print the tables in plain text (such as W command) or export them to CSV (there's no clipboard on Android).

In fact, there is no command-line nor cross-platform CSV editor, I wondered if a CSV editor with this same structure wouldn't be useful too.

Thanks.

**Comment by pedroalbanese** [comment]
Is it possible to implement the W command? It is possible to view and edit the files but there is no way to export them.

**Comment by howeyc** [comment]
Probably not, I haven't made any worthwhile updates or changes to this in many years. I doubt I'll be making any changes to it.

**Comment by pedroalbanese** [comment]
It is a pity. I didn't know the SC format as a Windows user and it is really difficult to use this format in Windows although so useful. I compiled the original SC but it depends on the Cygwin / MSYS terminal. I cannot compile to armel.

**Comment by pedroalbanese** [comment]
Is there a way to capture the terminal text and print it? What is the variable that is printed on the terminal by the termbox?

// Print a sheet.
func (s *Sheet) Print() error {
	if outfile, err := os.Create(s.Filename); err == nil {
		fmt.Fprintln(outfile, s.Contents)
		outfile.Close()
		return nil
	} else {
		return err
	}
}
